compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.2.1.cjs

npmScopes:
  'stayonhire':
    npmAlwaysAuth: true
    npmAuthToken: '${GITHUB_TOKEN}'
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmPublishRegistry: 'https://npm.pkg.github.com'
